version: '2.0'

services:
  logbot:
    image: logbot
    restart: unless-stopped
    volumes:
      - /home/k0nsl/logbot:/etc/logbot
    environment:
      - LOGBOT_SERVER=ragnarok.k0nsl.org
      - LOGBOT_CHANNELS=#k0nsl,#trinity,#thehax
      - LOGBOT_NICK=genericnondescripguy
    ports:
      - 15000:15000
