version: '2'

services:
  logbot:
    image: logbot
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - LOGBOT_SERVER=ragnarok.k0nsl.org
      - LOGBOT_CHANNELS=#k0nsl,#trinity,#thehax
      - LOGBOT_NICK=genericnondescripguy
    ports:
      - 15000:15000
